version: '3'
services:

  nginx-rev-proxy-setup:
    image: debian:stable-slim
    command: /tmp/nginx-rev-proxy-setup.sh
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/nginx-rev-proxy-setup.sh:/tmp/nginx-rev-proxy-setup.sh:ro

  redis:
    hostname: redis
    image: redis
    restart: always
    networks:
      default:
        aliases:
          - redis.internal

  db:
    hostname: db
    image: pmetpublic/lamp-db-server:no-password
    restart: always
    ports:
      - 3306
    volumes:
      - /data
    networks:
      default:
        aliases:
          - database.internal

  varnish:
    hostname: varnish
    image: pmetpublic/varnish
    restart: always
    # https://github.com/magento/magento2/issues/3897
    command: -f /etc/varnish/default.vcl -p feature=+esi_ignore_https
    ports:
      - 80
    volumes:
      - ./etc/varnish:/etc/varnish
    networks:
      default:
        aliases:
          - varnish.internal

  mq:
    hostname: mq
    image: rabbitmq:3.6.12
    restart: always
    networks:
      default:
        aliases:
          - mq.internal

  elasticsearch:
    hostname: elasticsearch
    image: pmetpublic/docker-elasticsearch:for-smile
    restart: always
    networks:
      default:
        aliases:
          - elasticsearch.internal

  app:
      container_name: ${MAGENTO_HOSTNAME}
      hostname: ${MAGENTO_HOSTNAME}
      image: pmetpublic/lamp-app-server:with-blackfire
      restart: always
      environment:
#        - COMPOSER_AUTH=${COMPOSER_AUTH}
#        - ENABLE_XDEBUG=${ENABLE_XDEBUG}
#        - ENABLE_DI_COMPILE=${ENABLE_DI_COMPILE}
        - XDEBUG_IDEKEY=${XDEBUG_IDEKEY}
        - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
#        - GMAIL_USERNAME_FOR_SSMTP=${GMAIL_USERNAME_FOR_SSMTP}
#        - GMAIL_PASSWORD_FOR_SSMTP=${GMAIL_PASSWORD_FOR_SSMTP}
#        - BLACKFIRE_CLIENT_ID=${BLACKFIRE_CLIENT_ID}
#        - BLACKFIRE_CLIENT_TOKEN=${BLACKFIRE_CLIENT_TOKEN}
#        - BLACKFIRE_SERVER_ID=${BLACKFIRE_SERVER_ID}
#        - BLACKFIRE_SERVER_TOKEN=${BLACKFIRE_SERVER_TOKEN}
        - MAGENTO_CLOUD_RELATIONSHIPS=${MAGENTO_CLOUD_RELATIONSHIPS}
        - MAGENTO_CLOUD_VARIABLES=${MAGENTO_CLOUD_VARIABLES}
        - MAGENTO_CLOUD_ROUTES=${MAGENTO_CLOUD_ROUTES}
      ports:
        - 80
      working_dir: /app
      volumes:
        # - ${HOME}/.composer:${HOME}/.composer
        - ./etc/cron.d/magento:/etc/cron.d/magento
        - ./etc/apache2/sites-enabled:/etc/apache2/sites-enabled
        # map php ini settings to cli and apache dirs
        - ./etc/php/7.0/templates:/etc/php/7.0/apache2/conf.d/templates
        - ./etc/php/7.0/apache2/conf.d/apache2.ini:/etc/php/7.0/apache2/conf.d/apache2.ini
        - ./etc/php/7.0/opcache.ini:/etc/php/7.0/apache2/conf.d/opcache.ini
        - ./etc/php/7.0/templates:/etc/php/7.0/cli/conf.d/templates
        - ./etc/php/7.0/cli/conf.d/cli.ini:/etc/php/7.0/cli/conf.d/cli.ini
        - ./etc/php/7.0/opcache.ini:/etc/php/7.0/cli/conf.d/opcache.ini
        - ./etc/blackfire/templates:/etc/blackfire/templates
        - ../../..:/app
        - /dev/null:/usr/sbin/ssmtp
        - /dev/null:/etc/my_init.d/blackfire.sh
      networks:
        default:
          aliases:
            - app.internal
      cap_add:
        - ALL
